openapi: 3.0.3
info:
  title: Claude MCP Hub Controller API
  version: 0.2.0
  description: Coordination for MCP hubs and toolchains.
paths:
  /health:
    get:
      tags: [MCP Hub Controller]
      summary: Health check
      responses:
        '200': { description: OK }
  /metrics:
    get:
      tags: [MCP Hub Controller]
      summary: Prometheus metrics
      responses:
        '200': { description: OK }
  /mcp/status:
    get:
      tags: [MCP Hub Controller]
      summary: MCP status
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status: { type: string }
                  hubs:
                    type: array
                    items: {}
  /mcp/command:
    post:
      tags: [MCP Hub Controller]
      summary: Send MCP command
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              additionalProperties: true
      responses:
        '202': { description: Accepted }
