openapi: 3.0.3
info:
  title: Claude Portfolio Manager API
  version: 0.1.0
paths:
  /health:
    get:
      summary: Health check
      responses:
        '200': { description: OK }
  /metrics:
    get:
      summary: Prometheus metrics
      responses:
        '200': { description: OK }
  /portfolio/holdings:
    get:
      summary: Get portfolio holdings
      responses:
        '200': { description: OK }
  /portfolio/rebalance:
    post:
      summary: Rebalance portfolio
      responses:
        '202': { description: Accepted }
