global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/alert_rules.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'agents'
    metrics_path: /metrics
    static_configs:
      - targets:
          - orchestrator:7001
          - portfolio-manager:7002
          - market-analyst:7003
          - risk-manager:7004
          - trade-executor:7005
          - notification-manager:7006
          - parameter-optimizer:7007
          - mcp-hub-controller:7008
