apiVersion: 1

deleteDatasources:
  - name: Loki
    type: loki

datasources:
  - name: Loki
    type: loki
    access: proxy
    orgId: 1
    url: http://loki:3100
    isDefault: false
    version: 1
    editable: false
