server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    static_configs:
      - targets: [localhost]
        labels:
          job: docker
          host: ${HOSTNAME}
          __path__: /var/lib/docker/containers/*/*-json.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            msg: msg
            service: service
            requestId: requestId
            traceId: traceId
            time: time
      - timestamp:
          source: time
          format: RFC3339
          fallback_formats: ['UnixMs']
      - labels:
          level:
          service:
          requestId:
          traceId:
      - output:
          source: msg
